# Generated by Django 4.1.7 on 2023-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_myuser_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.ImageField(max_length=250, null=True, upload_to='avatars/'),
        ),
    ]
