# Generated by Django 4.1.7 on 2023-03-11 11:44

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_myuser_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.ImageField(blank=True, help_text='Фото-аватар пользователя', max_length=250, null=True, upload_to=Users.models.user_directory_path),
        ),
    ]
