# Generated by Django 4.1.7 on 2023-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_myuser_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Требуется. Не более 150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
