# Generated by Django 4.1.7 on 2023-03-15 09:22

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_myuser_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_avatar',
            field=models.ImageField(blank=True, help_text='Путь файла: MEDIA_ROOT/user_id/category/filename', max_length=250, null=True, upload_to=Users.models.user_directory_path, verbose_name='Фотография пользователя.'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, verbose_name='username'),
        ),
    ]
