# Generated by Django 4.1.7 on 2023-03-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, default=12, max_length=150, verbose_name='username'),
            preserve_default=False,
        ),
    ]
