# Generated by Django 4.1.7 on 2023-03-19 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Группа')),
                ('description_group', models.CharField(blank=True, max_length=150, verbose_name='Описание группы')),
            ],
            options={
                'verbose_name': 'Группа задач',
                'verbose_name_plural': 'Группы задач',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('task_goal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цель задачи')),
                ('task_descriptions', models.TextField(blank=True, max_length=600, null=True, verbose_name='Описание задачи')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task_data_goal', models.DateField(verbose_name='Дата выполнения')),
                ('priority', models.CharField(choices=[('Неважные', 'Неважные и несрочные.'), ('Срочно-Неважные', 'Неважные и срочные.'), ('Важные', 'Важные и несрочные.'), ('Срочно-Важные', 'Важные и срочные.')], default='Неважные', max_length=15, verbose_name='Приоритет задачи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Task_Manager.taskgroups', verbose_name='Группа задачи')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='StagesOfExecuting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50, verbose_name='Описание подзадачи')),
                ('stage_name_status', models.BooleanField(default=False, verbose_name='Статус подзадачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task_Manager.task')),
            ],
            options={
                'verbose_name': 'Подпункт задачи',
                'verbose_name_plural': 'Подпункты задачи',
            },
        ),
    ]
