# Generated by Django 4.1.7 on 2023-03-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Task_Manager.taskgroups', verbose_name='Группа задачи'),
        ),
    ]
