# Generated by Django 4.1.7 on 2023-03-19 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task_Manager', '0002_alter_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgroups',
            name='creator_group',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель группы'),
            preserve_default=False,
        ),
    ]
