# Generated by Django 4.1.7 on 2023-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0003_taskgroups_creator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroups',
            name='group_name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
    ]
