# Generated by Django 4.1.7 on 2023-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0004_alter_taskgroups_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesofexecuting',
            name='stage_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание подзадачи'),
        ),
        migrations.AlterField(
            model_name='taskgroups',
            name='description_group',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='taskgroups',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название группы'),
        ),
    ]
